#!/bin/bash

general="general scripts"
config="bash configuration and aliases"
kali="Kali scripts"
error="Please enter either 'n' for 'no' or 'y' for 'yes'."

function copymsg(){
	echo "Copying all $1."
}

function donemsg(){
	echo "Done"
}

function cpgeneral(){
	copymsg "$general"
	sudo cp -r general/. /usr/local/bin/
	donemsg
}

function cpconfig(){
	copymsg "$config"
	sudo cp .bashrc .bash_aliases ~/
        donemsg
}

function cpkali(){
	echo "$kali are configured to use interface called 'wlan0' by default. Would you like to change the name of the interface? (y/n)"
	while read answer
        do
                if [ $answer == "y" ]
                then
                        echo "Enter the new interface name:"
			while read ans
			do
				./intconfig $ans
				break
			done
                        break
                elif [ $answer == "n" ]
                then
                        break
                else
                        echo $error
                        continue
                fi
        done
	copymsg "$kali"
	sudo cp -r kali-pen-test/. /usr/local/bin/
        donemsg
}

function run(){
	echo "Would you like to install $1? (y/n)"
	while read answer
	do
	        if [ $answer == "y" ]
	        then
	                $2
	                break
	        elif [ $answer == "n" ]
	        then
	                echo "Skipping."
                	break
        	else
	                echo $error
                	continue
        	fi
	done
}

run "$config" cpconfig
run "$general" cpgeneral
run "$kali" cpkali

echo "All done."

exit
