#!/bin/bash

general="general scripts"
config="bash configurations and aliases"
kali="Kali scripts"
dev="development scripts"
error="Please enter either 'n' for 'no' or 'y' for 'yes'."

function copymsg(){
	echo "Copying all $1."
}

function donemsg(){
	echo "Done"
}

function cpdir(){
	copymsg "$1"
	sudo cp -r $2/. /usr/local/bin/
	donemsg
}

function cpgeneral(){
	cpdir "$general" general
}

function cpconfig(){
	copymsg "$config" 
	sudo cp -r config/. ~/
	donemsg
}

function cpkali(){
	echo "$kali are configured to use interface called 'wlan0' by default. Would you like to change the name of the interface? (y/n)"
	while read answer
        do
                if [ $answer == "y" ]
                then
                        echo "Enter the new interface name:"
			while read interface
			do
				kali-pen-test/intconfig $interface
				break
			done
                        break
                elif [ $answer == "n" ]
                then
                        break
                else
                        echo $error
                        continue
                fi
        done
	cpdir "$kali" kali-pen-test
}

function run(){
	echo "Would you like to install $1? (y/n)"
	while read answer
	do
	        if [ $answer == "y" ]
	        then
	                $2
	                break
	        elif [ $answer == "n" ]
	        then
	                echo "Skipping."
                	break
        	else
	                echo $error
                	continue
        	fi
	done
}

if [ ! -z $1 ] && [ $1 == "--dev" ]
then
	cpdir "$dev" dev
fi

run "$config" cpconfig
run "$general" cpgeneral
run "$kali" cpkali

echo "All done."

exit
