#!/bin/bash

function cpgeneral(){
	echo "Copying all general scripts."
	sudo cp -r scripts/. /usr/local/bin/
	echo "Done."
}

function cpconfig(){
	echo "Copying all bash configuration and aliases."
	sudo cp .bashrc .bash_aliases ~/
        echo "Done."
}

function cpkali(){
	echo "Copying all kali scripts."
	sudo cp -r kali-pen-test/. /usr/local/bin/
        echo "Done."
}

function run(){
	echo "Would you like to install $1? (y/n)"
	while read answer
	do
	        if [ $answer == "y" ]
	        then
	                $2
	                break
	        elif [ $answer == "n" ]
	        then
	                echo "Skipping."
                	break
        	else
	                echo "Please enter either 'n' for 'no' or 'y' for 'yes'."
                	continue
        	fi
	done
}

run "bash configuration and aliases" cpconfig
run "general scripts" cpgeneral
run "Kali scripts" cpkali

exit
