#!/bin/bash

# The script will inevitably fail sometimes. You will then see a "SIOCSIFHWADDR: Operation not permitted" error.
# This can be for two reasons:
# 1) The randomly generated MAC address is invalid. Just keep running the script until you get one that works.
# 2) You have changed your MAC address in the last few minutes. Wait for a moment and try again.

if [ -z $1 ];
then
	mac=$(randmac)
else
	mac=$1
fi

oldMac=$(macof wlan0)

echo "Current MAC address: $oldMac"
sudo ifconfig wlan0 down
echo "Changing MAC address to $mac"
sudo ifconfig wlan0 hw ether $mac
sudo ifconfig wlan0 up
status=$(ifconfig | grep -c $oldMac)

if [[ status -eq 0 ]]
then
	echo "Change succesful!"
else
	echo "Operation failed. Wait a few minutes and try again."
fi


