#!/bin/bash

function push(){
	git status
	git add -A
	git commit -m $1
	git push
}

pushd .
cd ~/Documents/linux-scripts/
args=("$@")
echo "okay well, let's see what the hell is this $@"
push ${args[@]}
popd
