#!/bin/bash

name=$1
scriptdir="$(dirname $0)/"

[ -z $name ] && printf "ERROR: Please specify a name or path, e.g.:\n\tmkscript scriptname\n" && exit 1
[[ "$name" =~ "/" ]] && path="$name" || path=$scriptdir$name

function defaultEditor(){
	nano -l $1
}

function runEditor(){
	[ -z $EDITOR ] && defaultEditor $path || $EDITOR $path
}

echo "#!/bin/bash" > $path
chmod +x $path
runEditor && echo "Script created at path $path" && exit 0
