#!/bin/bash

process=$(ps -e | grep $1 | head -n 1 | awk '{print $1}')
[ -z $process ] && echo "Process matching '$1' not found." && exit 1

echo "Killing process:"
echo "$process"

processPid=$(echo $process | awk '{ print $1 }')
kill -9 $processPid
echo "Process killed."

exit
