#!/bin/bash

process=$(ps -e | grep $1)
[ -z $process ] && echo "Process matching '$1' not found." && exit 1

echo "Killing process:"
echo "$process"

kill $(echo $process | awk '{ print $1 }')
echo "Process killed."

exit
