#!/bin/bash

if [ -z $1 ]
then 
	echo "ERROR: Variable cannot be null!"
	exit 1
else
	filepath=/usr/local/bin/
	echo "#!/bin/bash" > $HOME/$1
	file=$HOME/$1
	sudo chmod +x $file
	sudo mv $file $filepath
	sudo nano -l /usr/local/bin/$1
fi
