#!/bin/bash

# Asks the question passed as an argument and loops until gets "y/yes" or "n/no" as an answer.

error="Please enter either 'n' for 'no' or 'y' for 'yes'."

echo $1

while read answer
do
	answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
	if [ $answer == "y" ] || [ $answer == "yes" ]
	then
		exit 0
	elif [ $answer == "n" ] || [ $answer == "no" ]
	then
		exit 1
	else
		echo $error
		continue
	fi
done
