#!/bin/bash

function errorPrompt(){
	printf 'This program requires Kotlin and Java. You can install them with the following commands:
	\n\tcurl -s https://get.sdkman.io | bash
	\n\tsource "$HOME/.sdkman/bin/sdkman-init.sh"
	\n\tsdk install kotlin
	\n\tsdk install java\n'
	false
}

if [ -z $1 ]; then
	echo -e "The argument cannot be null!"
	false
elif [ -f $1 ]; then
	newFile=$(sed 's/.kt/.jar/g' <<< $1)
	kotlinc $1 -include-runtime -d "$newFile" || errorPrompt
	true
else
	echo  "File '$1' not found."
	false
fi
