#!/bin/bash

error="Please enter either 'n' for 'no' or 'y' for 'yes'."
args="$@"

function getPath(){
        find ~/Documents/linux-scripts/ -name $1
}

function addNewScript(){
	echo "Warning: The file '$1' is not part of the project. Do you want to copy it anyway? (y/n)"
	while read answer
	do
		if [ $answer == "y" ]
		then
			echo "Into which directory do you want to copy the file?"
			directory=new/
			select choice in config dev general kali-pen-test
			do
				case $choice in
				config) directory=config/; break ;;
				dev) directory=dev/; break ;;
				general) directory=general/; break ;;
				kali-pen-test) directory=kali-pen-test/; break ;;
				*) echo "ERROR: Please choose a directory." ;;
				esac
			done
			cp /usr/local/bin/$1 ~/Documents/linux-scripts/$directory
			break
		elif [ $answer == "n" ]
		then
			break
		else
			echo $error
			continue
		fi
	done
}

function copyFiles(){
	IFS=' ' read -ra files <<< "$@"
        for i in "${files[@]}"
        do
                path=$(getPath $i)
                if [ -z $path ]
		then
                        addNewScript $i
                else
                        cp /usr/local/bin/$i $path
                fi
        done
}


if [ -z $1 ]
then
	echo "ERROR: You need to pass some files as arguments."
elif [ $1 == '--all' ] || [ $1 == '-a' ]
then
	array=( $( ls usr/local/bin/ ) )
	copyFiles "${array[@]}"
else
	copyFiles "${args[@]}"
fi

exit
