#!/bin/bash

args="$@"
dirPath=$HOME/Documents/linux-scripts/
path=$dirPath

function prompt(){
	yes-no-loop $1
}

function setDirPath(){
	echo "Searching for directory: 'linux-scripts'...";
	dirPath=$(find $HOME/ -name linux-scripts)
	echo "Done."
}

function setFilePath(){
        echo "Searching for file path: '$1'..."
	path=$(find $dirPath -name $1)
	echo "Done."
}

function addNewScript(){
	echo "Into which directory do you want to copy the file?"
	directory=new/
	select choice in config dev general kali-pen-test
	do
		case $choice in
		config) directory=config/; break ;;
		dev) directory=dev/; break ;;
		general) directory=general/; break ;;
		kali-pen-test) directory=kali-pen-test/; break ;;
		*) echo "ERROR: Please choose a directory." ;;
		esac
	done
	cp /usr/local/bin/$1 $dirPath/$directory
}

function copyFiles(){
	IFS=' ' read -ra files <<< "$@"
        for i in "${files[@]}"
        do
                setFilePath $i
                if [ -z $path ]
		then
			promptQuestion="Warning: The file '$1' is not part of the project. Do you want to copy it anyway? (y/n)"
                        prompt $promptQuestion && addNewScript $i
                else
                        cp /usr/local/bin/$i $path
                fi
        done
}

setDirPath

if [ -z $1 ]
then
	echo "ERROR: You need to pass some files as arguments."
	false
elif [ $1 == '--all' ] || [ $1 == '-a' ]
then
	array=( $( ls /usr/local/bin/ ) )
	copyFiles "${array[@]}"
else
	copyFiles "${args[@]}"
fi

exit
