#!/bin/bash

ifconfig
sudo ifconfig wlan0 down

if [ -z $1 ];
then
	mac=$(randmac)
else
	mac=$1
fi

echo "Changing MAC address to $mac."
sudo ifconfig wlan0 hw ether $mac
sudo ifconfig wlan0 up
ifconfig


