#!/bin/bash

echo "Entering monitor mode..."

sudo ifconfig wlan0 down

echo "Killing network processes:"
sudo airmon-ng check kill

sudo iwconfig wlan0 mode monitor

sudo ifconfig wlan0 up

iwconfig

echo "Complete."

exit
