#!/bin/bash

interface=$(getInterface)

function complete(){
	sudo ifconfig $interface up
	iwconfig
        echo "Complete."
}

if [ -z $1 ]
then
	echo "Entering monitor mode..."
	sudo ifconfig $interface down
	sudo airmon-ng check kill
	sudo iwconfig $interface mode monitor
	complete

elif [ $1 == "-r" ]
then
	echo "Reverting back to managed mode..."
	sudo ifconfig $interface down
	sudo iwconfig $interface mode managed
	complete
else
	echo "Error: Invalid command: $1."
	exit 1
fi

exit
