#!/bin/bash

interface=$(getInterface)

if [[ $1 = "-s" ]]
then
	monmod -r
	macspoof
fi
	
monmod
if [ -z $1 ] || [ $1 = "-s" ] # TODO this is suboptimal, needs to allow for -s even with other args
then
	airodump-ng $interface
else
	airodump-ng --bssid $1 --channel $2 --write $HOME/spoofiles/spoofile $interface
fi

