#!/bin/bash

function randHex(){
	num=$(randombtwn 0 255)
	num=$(echo "obase=16; ibase=10; $num" | bc)
	regex="^(0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F)$"
	if [[ $num =~ $regex ]]
	then
		num="0$num"
	fi
	echo $num
}

mac="$(randHex):"

for i in {1..4}
do
	var="$(randHex):"
        mac="$mac$var"
done

mac="$mac$(randHex)"

echo $mac

